In [1]:
from src.preprocess import Process_Binary_File
from datetime import datetime

In [4]:
pbf = Process_Binary_File()
YMD = datetime(2005, 2, 1)

In [5]:
pbf.execute(YMD=YMD, index=16)

,0,1,2,3,4,5,6,7,8,9,...,30,31,32,33,34,35,36,37,38,39
0,2005-02-01 00:00:01,1.145424e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.117549e+06,NaN,NaN,1.093913e+06,NaN,NaN,NaN
1,2005-02-01 00:00:02,1.145424e+07,9.392011e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.068272e+06,NaN,NaN,NaN,NaN,NaN,1.104459e+06,NaN,NaN
2,2005-02-01 00:00:03,NaN,9.392011e+06,7.956229e+06,6.872727e+06,NaN,NaN,NaN,NaN,NaN,...,NaN,1.068272e+06,NaN,1.150418e+06,1.083960e+06,NaN,NaN,NaN,1.738255e+06,NaN
3,2005-02-01 00:00:04,1.145424e+07,NaN,NaN,NaN,NaN,5.430127e+06,NaN,NaN,4.206933e+06,...,NaN,NaN,1.120381e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2005-02-01 00:00:05,NaN,9.392011e+06,NaN,6.872727e+06,NaN,NaN,NaN,NaN,NaN,...,NaN,1.099691e+06,NaN,1.150418e+06,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86395,2005-02-01 23:59:55,NaN,NaN,NaN,6.872727e+06,NaN,5.430127e+06,NaN,NaN,NaN,...,NaN,1.099691e+06,NaN,NaN,1.083960e+06,NaN,NaN,NaN,NaN,2.416244e+06
86396,2005-02-01 23:59:56,NaN,NaN,7.956229e+06,NaN,6.084211e+06,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.117549e+06,1.083960e+06,NaN,NaN,NaN,NaN,NaN
86397,2005-02-01 23:59:57,NaN,9.392011e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.120381e+06,NaN,1.083960e+06,NaN,NaN,NaN,NaN,NaN
86398,2005-02-01 23:59:58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.117549e+06,1.083960e+06,NaN,NaN,NaN,NaN,NaN
86399,2005-02-01 23:59:59,NaN,NaN,NaN,NaN,6.084211e+06,NaN,NaN,NaN,NaN,...,NaN,1.068272e+06,NaN,1.117549e+06,NaN,1.083626e+06,NaN,NaN,NaN,NaN